### ISSUE TITLE
Timeline Mission Control error

### ISSUE THREAD

**Issue by 503151695** [dji-sdk/Mobile-SDK-Android#99]
sdk4.0 samplecode    android6.0 M100

I keep three step :TakeOffStep GoToAction GoHomeAction 
like this:
        setTimelinePlanToText("Step 1: takeoff from the ground");
        elements.add(new TakeOffAction());

        setTimelinePlanToText("Step 3: Go 10 meters from home point");
        elements.add(new GoToAction(new LocationCoordinate2D(homeLatitude, homeLongitude), 10));
        
        setTimelinePlanToText("Step 6: go back home");
        elements.add(new GoHomeAction());

problem: GoHomeAction  will not be executed.  
       timeline running results show this:  
        GotoAction event is ELEMENT_STARTED.
        GotoAction event is ELEMENT_FINISHED. The execution 
        could not be executed.
       Timeline Event is FINISHED Failed: The 
       execution could not be  executed.

**Comment by GIS-HowardZhang** [comment]
Hi, @oliverou ,
Did your development team solve the problem in the new version sdk4.0.1?

**Comment by wtalleur** [comment]
I am also having this issue, only the first action is being executed, none after.

@oliverou Has this been fixed in SDK 4.0.1?

**Comment by talobin** [comment]
Hi all,

Thanks for reporting the issue.
4.0.1 still has this issue.
We are working on fixing this for the next release.

Thank you!

**Comment by visheshhartler** [comment]
Hi @oliverou 

I am facing the same issue with Timeline Mission. Is this issue been resolved in SDK 4.1.1?

**Comment by oliverou** [comment]
Hi @visheshhartler , we have just published the Android SDK 4.2, and this issue is resolved. Please download the latest SDK and try again.

**Comment by miladehghani** [comment]
@oliverou  I still have the problem with SDK version 4.2.1 :((((((( any suggestion?

**Comment by zoemcateedji** [comment]
4.3 was just released and contains many improvements to the Timeline Mission manager. Could load that version and let us know how it goes?
https://developer.dji.com/mobile-sdk/downloads/

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by Atlanta11** [comment]
Is the 10 for latitude or longitude? 
The aircraft go 10 meters in what direction?

elements.add(new GoToAction(new LocationCoordinate2D(homeLatitude, homeLongitude), 10));
